dotfiles_dir = "dotfiles"

[settings]

posthooks = [
    "zellij da -y"
]

[settings.dots]
# Gitconfig
gitconfig = { source = ".gitconfig", target = ".gitconfig" }

# Shell Setup
alacritty = { source = "shell/alacritty.toml", target = ".alacritty.toml" }
zellij = { source = "shell/zellij.kdl", target = ".config/zellij/config.kdl" }
zsh = { source = "shell/.zshrc", target = ".zshrc" }
starship = { source = "shell/starship.toml", target = ".config/starship.toml" }
